repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast # valid python
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: check-case-conflict
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: [ '--indent', '2', '--autofix' ]
      - id: check-shebang-scripts-are-executable
  #      - id: check-symlinks
  #      - id: debug-statements
  #      - id: no-commit-to-branch
  #        args: [ --branch, master, --branch, main ]
  #      - id: check-docstring-first

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.0.0
    hooks:
      - id: add-trailing-comma
        args: [ --py310-plus ]

  - repo: https://github.com/facebook/usort
    rev: v1.0.7
    hooks:
      - id: usort

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
      - id: pyupgrade
        args: [ --py310-plus ]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
      - id: autopep8

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [ "--max-line-length=140" ]
