FROM python:3.11 AS builder

WORKDIR /app

RUN python -m venv venv
RUN . venv/bin/activate

COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

FROM python:3.11-slim

LABEL maintainer="Hiro <laciferin@gmail.com>"
#only required for railway deployment
ARG RAILWAY_ENVIRONMENT
ENV RAILWAY_ENVIRONMENT=$RAILWAY_ENVIRONMENT
ENV PORT=8080

RUN echo $RAILWAY_ENVIRONMENT > ".env"

EXPOSE $PORT

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /app/venv /app/venv

RUN . venv/bin/activate

COPY . .

RUN pip install -r requirements.txt


ENTRYPOINT ["python","-m","uvicorn", "app:app", "--host", "0.0.0.0", "--port", $PORT, "--workers", "4"]

#https://medium.com/@rupertcarr/deploying-a-spring-boot-api-to-railway-using-maven-and-docker-5c75e7428e90
