name: Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  mode: testing
  env: ${{secrets.ENV}}


jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.11" ]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} on ${{matrix.os}}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Write environment
        run: |
          echo $env >> .env
          echo " MODE=$mode " >> .env
          source .env
          mv .env .env1

      - name: Install dependencies
        run: |
          #make install
          make install-tests

      - name: Lint with flake8
        run: |
          python -m pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Install test dependencies
        run: |
          python -m pip install pytest

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        timeout-minutes: 600
        with:
          # ssh-known-hosts: ${{ steps.read_pub_key.outputs.pub_key }}
          limit-access-to-actor: true
          limit-access-to-users: Nasfame,pythoneerHiro
      - name: Run tests
        run: |
          make test

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Dockerfile
        run: |
          docker build .
